
CREATE table TARJETA(ID_TARJETA INTEGER AUTO_INCREMENT PRIMARY KEY,NOMBRE VARCHAR(120),DIACORTE INTEGER);

CREATE table GASTOS(ID_GASTOS INTEGER AUTO_INCREMENT PRIMARY KEY,
ID_TARJETA INTEGER,FECHA DATE, CONCEPTO VARCHAR(500), CANTIDAD FLOAT,
 FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA(ID_TARJETA));

Select * from tarjeta;